name: Deploy to AWS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 16.x
    - name: Run npm install & fix
      run: |
       rm -rf node_modules 
       npm install -g npm@latest
    - name: Npm cache clean
      run: |
        npm cache verify
        npm cache clean --force
        npm audit fix --force
    - name: Run npm build 
      run: npm build
    - name: S3 Sync 
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
          args: --acl public-read --delete 
      env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'dist'
          
          
          
          
            
        
      
      
  
