name: Deploy to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup node.js environment 
        uses: actions/setup-node@v3.5.1
        
      - name: Npm install & npm build 
        run: | 
          npm install
          npm build 
      - name: S3 Sync 
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete 
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'dirs'
          
          
          
          
            
        
      
      
  
